# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Project CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install only prod dependencies
        run: npm install --production

      - name: Try compiling typescript with prod dependencies (matches EB behavior)
        run: npm run build

      - name: Install all dependencies (for CI)
        run: npm install

      - name: Check code formatting
        run: npx prettier --check .
