# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Project CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOSTNAME: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: rlynetwork
      POSTGRES_PASSWORD: password
      POSTGRES_DB_NAME: rewards

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: rlynetwork
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rewards
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 15

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Install only prod dependencies
        run: npm install --production

      - name: Try compiling typescript with prod dependencies (matches EB behavior)
        run: npm run build

      - name: Install all dependencies (for CI)
        run: npm install

      - name: Check code formatting
        run: npx prettier --check .

      - name: Setup Database
        run: npm run knex migrate:latest

      - name: Run Test Suite
        run: npm run test
